name: Welcome to prodigyErrCodes

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for submitting your issue to prodigyErrCodes!'
        pr-message: 'Thanks for submitting your pull request to prodigyErrCodes!'
